services:
  - type: web
    name: medibridge-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: PATIENT_APP_URL
        sync: false
      - key: DOCTOR_APP_URL
        sync: false
